version: '3'
services:
    api:
        build: ./backend
        ports:
            - "8080:8080"
        depends_on:
            - database
    client:
        build: ./frontend
        ports:
            - "3000:3000"
        depends_on:
            - api 
        stdin_open: true
#    localhost:
#        image: postgres
#        ports:
#            - "5432:5432"
#        environment:
#            - POSTGRES-ROOT-PASSWORD=123456789
#            - POSTGRES_PASSWORD=123456789
#            - POSTGRES_USER=postgres
#            - POSTGRES_DB=carservice