version: '3'
services:
    api:
        build: ./backend
        ports:
            - "8080:8080"
        depends_on:
            - mongo
    client:
        build: ./frontend
        ports:
            - "3000:3000"
        depends_on:
            - api
        stdin_open: true
    mongo:
        image: mongo
        restart: always
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: tank123
            MONGO_INITDB_ROOT_PASSWORD: tank123
